docato/docato/urls.py
from django.conf.urls import patterns, url

import views

urlpatterns = patterns('',
    url(r'^login/$', 'django.contrib.auth.views.login', { 'template_name': 'docato/login.html' }),
    url(r'^logout/$', 'django.contrib.auth.views.logout_then_login'),
    url(r'^$', views.Projects.as_view(), name = 'projects'),
    url(r'^project/(?P<proj_id>\d+)$', views.ProjectPage.as_view(), name = 'project'),
    url(r'^project/delete$', views.delete_projects, name = 'delete_projects'),
    url(r'^subject/(?P<subj_id>\d+)$', views.SubjectPage.as_view(), name = 'subject_page'),
    url(r'^subject/(?P<subj_id>\d+)/update$', views.update_subject, name = 'update_subject'),
    url(r'^subject/delete$', views.delete_subjects, name = 'delete_subjects'),
    
    url(r'^subject/(?P<subj_id>\d+)/typesystem$', views.TypeSystem.as_view(), name = 'typesystem'),
    url(r'^subject/(?P<subj_id>\d+)/typesystem/frametype/new$', views.NewFrameType.as_view(), name = 'add_frametype'),
    url(r'^subject/(?P<subj_id>\d+)/typesystem/frametype/list_json$', views.list_frametypes_json, name = 'list_frametypes_json'),
    url(r'^subject/(?P<subj_id>\d+)/typesystem/frametype/(?P<frametype_id>\d+)/update$', views.update_frametype, name = 'update_frametype'),
    url(r'^subject/(?P<subj_id>\d+)/typesystem/frametype/(?P<frametype_id>\d+)/delete$', views.delete_frametype, name = 'delete_frametype'),
    url(r'^subject/(?P<subj_id>\d+)/typesystem/frametype/(?P<frametype_id>\d+)/clone$', views.CloneFrameType.as_view(), name = 'clone_frametype'),
    url(r'^subject/(?P<subj_id>\d+)/typesystem/frametype/(?P<frametype_id>\d+)/slot/new$', views.add_slot, name = 'add_slot'),
    url(r'^subject/(?P<subj_id>\d+)/typesystem/frametype/(?P<frametype_id>\d+)/slot/(?P<slot_id>\d+)/update$', views.update_slot, name = 'update_slot'),
    url(r'^subject/(?P<subj_id>\d+)/typesystem/frametype/(?P<frametype_id>\d+)/slot/(?P<slot_id>\d+)/delete$', views.delete_slot, name = 'delete_slot'),
    
    url(r'^subject/(?P<subj_id>\d+)/search$', views.SearchFrameset.as_view(), name = 'search'),
    url(r'^subject/(?P<subj_id>\d+)/search/toolbar$', views.SearchToolbar.as_view(), name = 'search_toolbar'),
    
    url(r'^subject/(?P<subj_id>\d+)/summary', views.Summary.as_view(), name = 'summary'),
    url(r'^subject/(?P<subj_id>\d+)/analysis$', views.Analysis.as_view(), name = 'analysis'),
    
    url(r'^subject/(?P<subj_id>\d+)/document/delete$', views.delete_docs, name = 'delete_doc'),
    url(r'^subject/(?P<subj_id>\d+)/document/(?P<doc_id>\d+)$', views.Doc.as_view(), name = 'view_doc'),
    url(r'^subject/(?P<subj_id>\d+)/document/(?P<doc_id>\d+)/extracted_data$', views.get_extracted_data, name = 'extracted_data'),
    url(r'^subject/(?P<subj_id>\d+)/document/(?P<doc_id>\d+)/converted$', views.converted_doc, name = 'converted_doc'),
    url(r'^subject/(?P<subj_id>\d+)/document/(?P<doc_id>\d+)/frame/add$', views.add_frame, name = 'add_frame'),
    url(r'^subject/(?P<subj_id>\d+)/document/(?P<doc_id>\d+)/frame/rename$', views.rename_frame, name = 'rename_frame'),
    url(r'^subject/(?P<subj_id>\d+)/document/(?P<doc_id>\d+)/frame/delete$', views.delete_frames, name = 'delete_frames'),
    url(r'^subject/(?P<subj_id>\d+)/document/(?P<doc_id>\d+)/frame/add_cues$', views.add_cues, name = 'add_cues'),
    url(r'^subject/(?P<subj_id>\d+)/document/(?P<doc_id>\d+)/frame/delete_cue$', views.delete_cue, name = 'delete_cue'),
    url(r'^subject/(?P<subj_id>\d+)/document/(?P<doc_id>\d+)/frame/update_sval_value$', views.update_sval_value, name = 'update_sval_value'),
    url(r'^subject/(?P<subj_id>\d+)/document/(?P<doc_id>\d+)/frame/get_value_variants$', views.get_value_variants, name = 'get_value_variants'),
    url(r'^subject/(?P<subj_id>\d+)/document/(?P<doc_id>\d+)/frame/add_list_value$', views.add_list_value, name = 'add_list_value'),
    url(r'^subject/(?P<subj_id>\d+)/document/(?P<doc_id>\d+)/frame/delete_list_value$', views.delete_list_value, name = 'delete_list_value'),
    
    url(r'^search_empty$', views.SearchEmpty.as_view(), name = 'search_empty'),
    url(r'^search/(?P<eng_id>\d+)/(?P<query>.*)$', views.do_search, name = 'do_search'),
)

docato/docato_proj/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

import settings

js_info_dict = {
    'packages': ('docato',),
}

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('docato.urls')),
    url(r'^jsi18n/$', 'django.views.i18n.javascript_catalog', js_info_dict),
    url(r'^i18n/', include('django.conf.urls.i18n')),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}))

docato/docato/models.py
import logging, numpy as np, scipy.sparse
from lazy import lazy

from django.utils.translation import ugettext_lazy as _
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Q
from django.db.models.signals import post_delete, pre_delete
from django.db import IntegrityError
from django.dispatch import receiver
from django.conf import settings

from polymorphic.models import PolymorphicModel

from docato.utils import get_unique_model_name, try_get_reference, get_value, ValuesTypes

logger = logging.getLogger('common')

###############################################################################
############################### Projects ######################################
###############################################################################
class Project(models.Model):
    name = models.CharField(max_length = 255, verbose_name = _('Name'), unique = True)
    desc = models.CharField(max_length = 1000, verbose_name = _('Description'), blank = True)

    def __unicode__(self):
        return self.name
    
    class Meta:
        permissions = (
                       ('can_access', _('Can view project contents')),
                       ('can_add_or_remove_subjects', _('Can add or remove subjects')),
                       )


class Subject(models.Model):
    project = models.ForeignKey(Project, related_name = 'subjects')
    name = models.CharField(max_length = 255,
                            verbose_name = _('Name'))
    timestamp = models.DateTimeField(verbose_name = _('Timestamp'))
    allow_sval_cascade_delete = models.BooleanField(default = False,
                                                    verbose_name = _('Allow delete slots (with cascade deletion of values)'))

    class Meta:
        unique_together = ('name', 'project')
        permissions = (
                       ('can_add_docs', _('Can upload documents')),
                       ('can_edit_docs', _('Can edit documents markup')),
                       ('can_edit_typesystem', _('Can edit typesystem')),
                       )

    def __unicode__(self):
        return self.name

    def embedded_frames_ids(self):
        return set(v.value.id for v in
                   ObjectSlotValue.objects.filter(frame__doc__subject = self)
                   if isinstance(v.slot, ObjectSlot) and v.slot.embedded and not v.value is None)
    
    def circular_dependency_exists(self):
        types_map = { t.id : idx for idx, t in enumerate(self.types.all()) }
        graph = np.zeros((len(types_map), len(types_map)))
        graph.fill(np.nan)
        for frametype in self.types.all():
            src_idx = types_map[frametype.id]
            for slot in frametype.slots.instance_of(ObjectSlot):
                if slot.embedded:
                    if slot.value_type == frametype:
                        return True
                    graph[src_idx, types_map[slot.value_type.id]] = 1
        paths = scipy.sparse.csgraph.floyd_warshall(graph)
        for i in xrange(len(types_map)):
            for j in xrange(i + 1, len(types_map)):
                if paths[i, j] != np.inf and paths[j, i] != np.inf:
                    return True
        return False


###############################################################################
################################# Search ######################################
###############################################################################
class SearchEngine(models.Model):
    name = models.CharField(max_length = 200, unique = True, verbose_name = _('Name'))
    template_name = models.CharField(max_length = 100, default = 'redirect.html')
    kwargs = models.CharField(max_length = 2000, blank = True)

    def __unicode__(self):
        return self.name


class SavedSearch(models.Model):
    user = models.ForeignKey(User, related_name = 'searches')
    subject = models.ForeignKey(Subject, related_name = 'searches')
    query = models.CharField(max_length = 300)

    def __unicode__(self):
        return self.query


###############################################################################
############################### Documents #####################################
###############################################################################
class Document(models.Model):
    class States:
        NOT_ANALYZED = 0
        ANALYZED = 1
        ERROR = -1
    STATE_CHOICES = (
                     (States.NOT_ANALYZED, _('Not analyzed yet')),
                     (States.ANALYZED, _('Analyzed successfully')),
                     (States.ERROR, _('Error occurred during analysis')),
                     )
    UPLOAD_TO = 'src'

    subject = models.ForeignKey(Subject, related_name = 'docs', verbose_name = _('Subject'))

    url = models.CharField(max_length = 4000, blank = True, verbose_name = _('URL'))
    title = models.CharField(max_length = 255, verbose_name = _('Title'))
    authors = models.CharField(max_length = 300, blank = True, verbose_name = _('Authors'))
    content_type = models.CharField(max_length = 100, blank = True, verbose_name = _('Content type'))

    source_file = models.FileField(upload_to = UPLOAD_TO, max_length = 300, blank = True, verbose_name = _('Source file'))
    converted_content = models.TextField(verbose_name = _('Content'))
    state = models.IntegerField(choices = STATE_CHOICES, default = States.NOT_ANALYZED, verbose_name = _('State'))

    load_time = models.DateTimeField(verbose_name = _('Load time'))

    @property
    def all_cues(self):
        return Cue.objects.filter(slot_value__frame__doc = self)

    def delete(self):
        for frame in self.frames.all():
            frame.delete()
        super(Document, self).delete()

    @property
    def embedded_frames_ids(self):
        return set(v.value.id for v in
                   ObjectSlotValue.objects.filter(frame__doc = self)
                   if isinstance(v.slot, ObjectSlot) and v.slot.embedded and not v.value is None)
    
    @property
    def standalone_frames(self):
        return self.frames.filter(~Q(id__in = self.embedded_frames_ids))

    def __unicode__(self):
        return self.title

    class Meta:
        unique_together = ('subject', 'title')


@receiver(post_delete, sender = Document)
def del_source_file(sender, instance = None, **kwargs):
    try:
        instance.source_file.delete(save = False)
    except Exception as ex:
        logger.error('Could not delete source file %s: %r' % (instance.source_file.url, ex))


###############################################################################
################################# Types #######################################
###############################################################################
class FrameType(models.Model):
    subject = models.ForeignKey(Subject, related_name = 'types')
    name = models.CharField(max_length = 200,
                            verbose_name = _('Name'))
    standalone = models.BooleanField(default = True,
                                     verbose_name = _('Standalone'))

    def can_delete(self):
        return (not self.instances.all().exists()) \
            and (not self.references.all().exists())

    def delete(self):
        for slot in self.slots.all():
            slot.delete()
        super(FrameType, self).delete()

    def clone(self):
        new_name = get_unique_model_name(self.subject.types.all(),
                                         _('Copy of ') + self.name)
        result = self.subject.types.create(name = new_name,
                                           standalone = self.standalone)
        for slot in self.slots.all():
            def_args = {
                        'frame_type' : result,
                        'name' : slot.name,
                        'description' : slot.description
                        }
            if isinstance(slot, ObjectSlot):
                def_args['value_type'] = slot.value_type
                def_args['embedded'] = slot.embedded
            else:
                def_args['default_value'] = slot.default_value
            type(slot).objects.create(**def_args)
        return result
    
    def get_new_slot_order(self):
        greatest_order = self.slots.order_by('-order').values('order').first()
        return 10 if greatest_order is None else (greatest_order['order'] + 10)

    class Meta:
        unique_together = ('subject', 'name')


class BaseSlot(PolymorphicModel):
    frame_type = models.ForeignKey(FrameType,
                                   related_name = 'slots')
    name = models.CharField(max_length = 255,
                            verbose_name = _('Name'))
    description = models.TextField(blank = True,
                                   default = _('Some description'))
    order = models.IntegerField(default = 0,
                                verbose_name = _('Order'))

    @property
    def is_list_slot(self):
        return False

    def ensure_objects_containment(self):
        for frame in self.frame_type.instances.all():
            if not frame.slots.filter(slot = self).exists():
                frame.create_slot_value(self)

    def delete(self, *args, **kwargs):
        if self.values.exists() and not self.frame_type.subject.allow_sval_cascade_delete:
            raise IntegrityError(_('Slot values cascade deletion is not allowed!'))
        for sval in self.values.all():
            sval.delete()
        super(BaseSlot, self).delete()

    def __unicode__(self):
        return '%s.%s' % (self.frame_type.name, self.name)
    
    class Meta:
        unique_together = ('frame_type', 'name')


class ClassLabelSlot(BaseSlot):
    template_name = 'docato/typesystem/slots/class_label.html'
    type_name = _('Class Label')
    
    default_value = models.CharField(max_length = 200,
                                     default = "-")


class ClassLabelListSlot(ClassLabelSlot):
    type_name = _('List of class labels')
    
    @property

docato/docato/forms.py
import logging
from django import forms as djforms
from django.utils.translation import ugettext

import models

logger = logging.getLogger('common')

class NewProjectForm(djforms.ModelForm):
    class Meta:
        model = models.Project
        fields = ['name']


class NewSubjectForm(djforms.ModelForm):
    class Meta:
        model = models.Subject
        fields = ['name', 'project', 'timestamp']
        widgets = {
                   'project': djforms.HiddenInput(),
                   'timestamp': djforms.HiddenInput()
                   }


class AddDocumentForm(djforms.ModelForm):
    def clean(self):
        cleaned_data = super(AddDocumentForm, self).clean()
        if not (cleaned_data['title'] or cleaned_data['source_file']):
            raise djforms.ValidationError(_('You must specify URL or File or both'))
        return cleaned_data 

    class Meta:
        model = models.Document
        fields = ('title', 'url', 'source_file')
        widgets = {
                   'title': djforms.TextInput(attrs = { 'maxlength' : '255' }),
                   'url': djforms.TextInput(attrs = { 'maxlength' : '4000' }),
                   }


class NewFrameForm(djforms.Form):
    #parent_id = djforms.CharField(widget = djforms.HiddenInput)
    type = djforms.TypedChoiceField(coerce = int)
    
    def __init__(self, types, *args, **kwargs):
        super(NewFrameForm, self).__init__(*args, **kwargs)
        self.fields['type'].choices = types


# class AddSlotValueForm(djforms.ModelForm):
#     class Meta:
#         model = models.SlotValue
# 
# 
# class FindSlotValueForm(djforms.Form):
#     proj_id = djforms.IntegerField()
#     slot_id = djforms.IntegerField()
#     query = djforms.CharField(required = False)

docato/docato/templates/docato/analysis.html
{% extends "docato/logged_in_base.html" %}
{% load staticfiles %}
{% load i18n %}

{% block extrahead %}
	{{ block.super }}
	<link rel="stylesheet" type="text/css" href="{% static "docato/css/analysis.css" %}">
{% endblock extrahead %}

{% block content %}

<span id="subject_id" class="hidden">{{ subject.id }}</span>

<div class="panel" id="subject_info">
	<h1><a href="{% url 'subject_page' subject.id %}">{% trans 'Subject' %}: {{ subject.name }}</a></h1>
</div>

<div class="panel" id="analysis_wrapper">
	{% trans 'Some tools to analyze the feature table' %}
</div>

{% endblock content %}

docato/docato/templates/docato/base.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
{% load staticfiles %}
{% load i18n %}
{% load bootstrap3 %}
<html>
<head>
	<title>
		{% block page_title %}
		{% trans "Information extraction helper" %}
		{% endblock page_title %}
	</title>
	
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">

	{% block extrahead %}
		{% bootstrap_css %}
        <link rel="stylesheet" type="text/css" href="{% static "docato/css/base.css" %}">
        <link rel="stylesheet" type="text/css" href="{% static "docato/css/jquery-ui-1.10.3.custom.css" %}">
		<link rel="stylesheet" type="text/css" href="{% static "docato/css/interactive_table.css" %}">

		
		<script type="text/javascript" src="{% url 'django.views.i18n.javascript_catalog' %}"></script>
		<script type="text/javascript" src="{% bootstrap_jquery_url %}"></script>
        <script type="text/javascript" src="{% static "docato/js/jquery-ui-1.10.3.custom.js" %}"></script>
        {% bootstrap_javascript %}
        <script type="text/javascript" src="{% static "docato/js/bootbox.min.js" %}"></script>
        <script type="text/javascript" src="{% static "docato/js/base.js" %}"></script>
        <script type="text/javascript" src="{% static 'docato/js/table_events.js' %}"></script>
        
    {% endblock extrahead %}
</head>
<body class="docato">
	<div id="global_wrapper">
		<nav class="navbar navbar-default" role="navigation">
			<div class="container-fluid">
				<div class="navbar-header navbar-brand">
			      	{% trans 'Information extraction helper' %}
			    </div>
			    
			    <ul class="nav navbar-nav">
				    {% block navbar %}
				    {% endblock navbar %}
			    </ul>

			    <form id="choose_language" class="navbar-right" action="{% url 'set_language' %}" method="post">
				        {% csrf_token %}
			        <input name="language" type="hidden" value="{{ LANGUAGE_CODE }}" />
			        <ul class="nav navbar-nav">
		            {% for lang in LANGUAGES %}
	            		{% if LANGUAGE_CODE == lang.0 %}
	                        <li class="active"><a href="javascript:void(0)" class="bold_label">{% trans lang.1 %}</a></li>
	                    {% else %}
	                        <li><a class="setlang_{{ lang.0 }}" href="javascript:void(0)">{{ lang.1 }}</a></li>
	                    {% endif %}
		            {% endfor %}
		            </ul>
			    </form>

			    <ul class="nav navbar-nav navbar-right">
			    	{% if user.is_authenticated %}
			        <li><a href="{% url 'django.contrib.auth.views.logout_then_login' %}">{% trans 'Log out' %}</a></li>
			        {% else %}
			        <li><a href="{% url 'django.contrib.auth.views.login' %}">{% trans 'Login' %}</a></li>
			        {% endif %}
		      	</ul>
		    </div>
	    </nav>
		
        
        <div id="content">
			{% block content %}
			{% endblock content %}
		</div>
		
		{% if not hide_footer %}
		<div id="footer">
            {% block footer %}
                <div id="copyright">
                    © 2013 {% trans "Lab.02" %}
                    <a href="http://www.isa.ru">{% trans "ISA RAS" %}</a>.
                </div>
            {% endblock footer %}
        </div>
        {% endif %}
	</div>
</body>
</html>

docato/docato/templates/docato/login.html
{% extends "docato/base.html" %}
{% load staticfiles %}
{% load i18n %}
{% load bootstrap3 %}

{% block extrahead %}
	{{ block.super }}
	<link rel="stylesheet" type="text/css" href="{% static "docato/css/login.css" %}">
{% endblock extrahead %}

{% block content %}

<div id="login_wrapper">
	{% if form.errors %}
		<div id="login_error">{% trans "The entered login and password don't meet each other." %}</div>
	{% endif %}
	
	<form method="post" action="{% url 'django.contrib.auth.views.login' %}">
		{% csrf_token %}
		{% bootstrap_form form %}
		<button type="submit" class="btn btn-default">{% trans "Log in" %}</button>
		<input type="hidden" name="next" value="{% if next %}{{ next }}{% else %}{% url 'projects' %}{% endif %}" />
	</form>
</div>

{% endblock content %}

docato/docato/templates/docato/main.html
{% extends "docato/base.html" %}
{% load staticfiles %}
{% load render_table from django_tables2 %}
{% load i18n %}

{% block extrahead %}
	{{ block.super }}
	<link rel="stylesheet" type="text/css" href="{% static "docato/css/interactive_table.css" %}">
	<link rel="stylesheet" type="text/css" href="{% static "docato/css/main.css" %}">

	<script type="text/javascript" src="{% static 'docato/js/table_events.js' %}"></script>
	<script type="text/javascript" src="{% static 'docato/js/main.js' %}"></script>
{% endblock extrahead %}

{% block content %}
<div class="panel">
	<h1>{% trans 'Open new subject' %}</h1>
	
	<form id="new_subject" action="{% url 'new_subject' %}" method="post">
		{% csrf_token %}
		<label for="{{ new_subj_form.name.auto_id }}">{% trans 'Please enter name of the new subject' %}</label>
		{{ new_subj_form.name }}
		<input type="submit" value="{% trans 'Create new subject' %}" />
	</form>
</div>

<div class="panel">
<h1>{% trans 'Already investigated subjects' %}</h1>
{% render_table table %}
<a href="javascript:void(0)" class=".ajax_link" id="delete_subjects">{% trans 'Delete the selected subjects' %}</a>
</div>

{% endblock content %}

docato/docato/templates/docato/project.html
{% extends "docato/base.html" %}
{% load i18n %}
{% load bootstrap3 %}
{% load guardian_tags %}
{% load render_table from django_tables2 %}

{% block navbar %}
	<li><a href="{% url 'projects' %}">{% trans 'Projects' %}</a></li>
	<li class="active"><a href="javascript:void(0)">{{ project.name }}</a></li>
{% endblock navbar %}

{% block content %}
	{% get_obj_perms user for project as "project_perms" %}
	<div class="container">
		{% if 'can_add_or_remove_subjects' in project_perms %}
		<div class="row panel panel-default">
			<div class="panel-heading">
				<b>{% trans 'Add new subject' %}</b>
			</div>
			<div class="panel-body">
				<form method="POST">
					{% csrf_token %}
					{% bootstrap_form form %}
					<button type="submit" class="btn btn-default">{% trans 'Create new subject' %}</button>
				</form>
			</div>
		</div>
		{% endif %}

		<div class="row panel panel-default">
			<div class="panel-heading">
				<b>{% trans 'Subjects' %}</b>
			</div>
			<div class="panel-body">
				{% render_table table %}
				{% if 'can_add_or_remove_subjects' in project_perms %}
				<a href="javascript:void(0)" class="ajax_link" id="delete_subjects">{% trans 'Delete the selected subjects' %}</a>
				{% endif %}
			</div>
		</div>
	</div>
	<script type="text/javascript">
		jQuery(document).ready(function ($) {
			new TableEvents({
				table: '.docato #subjects',
				delete_button : '#delete_subjects',
				delete_url : "{% url 'delete_subjects' %}",
				get_row_link : function () {
					return '../subject/' + $(this).find('.select input').attr('value');
				}
			});
		});
	</script>
{% endblock content %}

docato/docato/templates/docato/projects.html
{% extends "docato/base.html" %}
{% load i18n %}
{% load bootstrap3 %}
{% load guardian_tags %}
{% load render_table from django_tables2 %}

{% block navbar %}
	<li class="active"><a href="javascript:void(0)">{% trans 'Projects' %}</a></li>
{% endblock navbar %}

{% block content %}
	<div class="container">
		{% if perms.med_web_helper.add_project %}
		<div class="row panel panel-default">
			<div class="panel-heading">
				<b>{% trans 'Add new project' %}</b>
			</div>
			<div class="panel-body">
				<form method="POST">
					{% csrf_token %}
					{% bootstrap_form form %}
					<button type="submit" class="btn btn-default">{% trans 'Create new project' %}</button>
				</form>
			</div>
		</div>
		{% endif %}

		<div class="row panel panel-default">
			<div class="panel-heading">
				<b>{% trans 'Projects' %}</b>
			</div>
			<div class="panel-body">
				{% render_table table %}
				{% if perms.med_web_helper.del_project %}
				<a href="javascript:void(0)" class="ajax_link" id="delete_projects">{% trans 'Delete the selected projects' %}</a>
				{% endif %}
			</div>
		</div>
	</div>
	<script type="text/javascript">
		jQuery(document).ready(function ($) {
			new TableEvents({
				table: '.docato #projects',
				delete_button : '#delete_projects',
				delete_url : "{% url 'delete_projects' %}",
				get_row_link : function () {
					return 'project/' + $(this).find('.select input').attr('value');
				}
			});
		});
	</script>
{% endblock content %}

docato/docato/templates/docato/search_empty.html
{% load staticfiles %}
{% load i18n %}
<html>
<head>
	<link rel="stylesheet" type="text/css" href="{% static "docato/css/search_empty.css" %}">
</head>
<body>
	<h1>{% trans 'Please enter the query in the form above and press search button' %}</h1>
</body>
</html>

docato/docato/templates/docato/search_frameset.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/frameset.dtd">
{% load i18n %}
<html>
<head>
	<title>
		{% trans "Information extraction helper" %}
	</title>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
</head>

<frameset rows="295,*" cols="*" frameborder="0" framespacing="0">
    <frame src="{% url 'search_toolbar' subj_id %}" scrolling="no" noresize>
   	<frame src="{% url 'search_empty' %}" name="browserFrame">
   	<noframes>{% trans 'This application needs frames enabled to work properly' %}</noframes>
</frameset>

</html>